### ISSUE TITLE
uuid7s

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/discord-scheduler#8]
UUIDv7 has been accepted: https://www.rfc-editor.org/rfc/rfc9562 do you want to advertise this as providing uuids?

**Comment by mikeshardmind** [comment]
Oh cool, I didn't see that was accepted. I'll need to double-check that the implementation still matches what was accepted, if it does, I'll consider advertising it as a uuid with clear details, but I need to think about if I want to lock into that or not.

**Comment by mikeshardmind** [comment]
I've decided to explicitly avoid guaranteeing these remain as uuids for now.

I've updated the language used in a few places, and slightly more strongly hinted at "don't use this outside this library" in 615f8dc
